[INFO 22:00:54] root Saving to FileStorageObserver in results/sacred.
[DEBUG 22:00:54] pymarl Using capture mode "fd"
[INFO 22:00:54] pymarl Running command 'my_main'
[INFO 22:00:54] pymarl Started run with ID "7"
[DEBUG 22:00:54] my_main Started
[WARNING 22:00:54] my_main CUDA flag use_cuda was switched OFF automatically because no CUDA devices are available!
[INFO 22:00:54] my_main Experiment Parameters:
[INFO 22:00:54] my_main 

{   'action_selector': 'epsilon_greedy',
    'agent': 'rnn',
    'agent_output_type': 'q',
    'batch_size': 32,
    'batch_size_run': 1,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'critic_lr': 0.0005,
    'double_q': True,
    'env': 'sc2',
    'env_args': {   'continuing_episode': False,
                    'debug': False,
                    'difficulty': '7',
                    'game_version': None,
                    'heuristic_ai': False,
                    'heuristic_rest': False,
                    'map_name': '3s5z',
                    'move_amount': 2,
                    'obs_all_health': True,
                    'obs_instead_of_state': False,
                    'obs_last_action': False,
                    'obs_own_health': True,
                    'obs_pathing_grid': False,
                    'obs_terrain_height': False,
                    'obs_timestep_number': False,
                    'replay_dir': '',
                    'replay_prefix': '',
                    'reward_death_value': 10,
                    'reward_defeat': 0,
                    'reward_negative_scale': 0.5,
                    'reward_only_positive': True,
                    'reward_scale': True,
                    'reward_scale_rate': 20,
                    'reward_sparse': False,
                    'reward_win': 200,
                    'seed': 517917672,
                    'state_last_action': True,
                    'state_timestep_number': False,
                    'step_mul': 8},
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hypernet_embed': 64,
    'hypernet_layers': 2,
    'label': 'default_label',
    'learner': 'q_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.0005,
    'mac': 'basic_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'qmix',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'repeat_id': 1,
    'rnn_hidden_dim': 64,
    'runner': 'episode',
    'runner_log_interval': 10000,
    'save_model': False,
    'save_model_interval': 2000000,
    'save_replay': False,
    'seed': 517917672,
    't_max': 2050000,
    'target_update_interval': 200,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'use_cuda': False,
    'use_tensorboard': False}

[ERROR 22:00:54] pymarl Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "main.py", line 35, in my_main
    run(_run, config, _log)
  File "/Users/codeman/projects/pymarl/run.py", line 48, in run
    run_sequential(args=args, logger=logger)
  File "/Users/codeman/projects/pymarl/run.py", line 79, in run_sequential
    runner = r_REGISTRY[args.runner](args=args, logger=logger)
  File "/Users/codeman/projects/pymarl/runners/episode_runner.py", line 15, in __init__
    self.env = env_REGISTRY[self.args.env](**self.args.env_args)
  File "/Users/codeman/projects/pymarl/envs/__init__.py", line 7, in env_fn
    return env(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'obs_timestep_number'
